services:
  postgres:
    build: docker/SQL
    container_name: UserDB
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: temppassword
      POSTGRES_DB: usersdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  mongo:
    container_name: ArticleDB
    build: docker/MongoDb
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: temppassword
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379


volumes:
  postgres_data: