services:
  postgres:
    build: docker/SQL
    container_name: UserDB
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRESUSER}
      POSTGRES_PASSWORD: ${POSTGRESPASSWORD}
      POSTGRES_DB: usersdb
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql

  mongo:
    container_name: ArticleDB
    build: docker/MongoDb
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODBUSERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODBPASSWORD}
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
  userservice:
    image: userservice
    container_name: userservice
    restart: always
    ports:
      - 8080:8080
    build: 
      context: Backend/UserService
      dockerfile: UserService/Dockerfile


volumes:
  postgres_data: