services:
  postgres:
    build: docker/SQL
    container_name: UserDB
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRESUSER}
      POSTGRES_PASSWORD: ${POSTGRESPASSWORD}
      POSTGRES_DB: usersdb
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - herald-network

  mongodb:
    container_name: ArticleDB
    build: docker/MongoDb
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODBUSERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODBPASSWORD}
    networks:
      - herald-network
  redis:
    image: redis
    container_name: redis-cache
    restart: always
    ports:
      - 6379:6379
    networks:
      - herald-network
  user-service:
    image: user-service
    container_name: user-service
    restart: always
    ports:
      - 8080:8080
    build: 
      context: Backend/UserService
      dockerfile: UserService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=${ENVIRONMENT}
      - ConnectionStrings__PostgresDb=${PostgresConnectionString}
      - JwtTokenInformation__TokenKey=${JwtToken}
      - JwtTokenInformation__Issuer=${JwtIssuer}
      - JwtTokenInformation__Audience=${JwtAudience}
      - JwtTokenInformation__ExpiryTime=${JwtExpiryTime}
    depends_on:
      - postgres
      - set-up
    networks:
      - herald-network

  article-service:
    image: article-service
    container_name: article-service
    restart: always
    ports:
      - 8081:8080
    build: 
      context: Backend/ArticleService
      dockerfile: ArticleService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=${ENVIRONMENT}
      - ConnectionStrings__MongoDb=${MongoDbConnectionString}
      - JwtTokenInformation__TokenKey=${JwtToken}
      - JwtTokenInformation__Issuer=${JwtIssuer}
      - JwtTokenInformation__Audience=${JwtAudience}
    depends_on:
      - postgres
      - mongodb
      - redis
      - user-service
      - set-up
    networks:
      - herald-network
    
  set-up:
    image: set-up
    container_name: set-up
    restart: always
    ports:
      - 8082:8080
    build: 
      context: Setup/SetUp
      dockerfile: SetUp/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=${ENVIRONMENT}
      - ConnectionStrings__PostgresDb=${PostgresConnectionString}
      - ConnectionStrings__MongoDb=${MongoDbConnectionString}
      - CsvLocations__UsersCsv=SyntheticData/users.csv
      - CsvLocations__ArticlesCsv=SyntheticData/articles.csv
    depends_on:
      - postgres
      - mongodb
    networks:
      - herald-network

networks:
  herald-network:
    driver: bridge

volumes:
  postgres_data: