name: Docker Compose

on:
  push:
    branches: ['**']
  pull_request:
    branches: [ '**' ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Run docker compose
              uses: hoverkraft-tech/compose-action@3846bcd61da338e9eaaf83e7ed0234a12b099b72
              env:
                POSTGRESUSER: ${{ secrets.POSTGRES_USER }}
                POSTGRESPASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
                MONGODBUSERNAME: ${{ secrets.MONGODB_USERNAME }}
                MONGODBPASSWORD: ${{ secrets.MONGODB_PASSWORD }}
                ENVIRONMENT: Development
                PostgresConnectionString: Host=postgres;Port=5432;Database=usersdb;Username=${{ secrets.POSTGRES_USER }};Password=${{ secrets.POSTGRES_PASSWORD }}
                MongoDbConnectionString: mongodb://${{ secrets.MONGODB_USERNAME }}:${{ secrets.MONGODB_PASSWORD }}@mongodb:27017/articlesDB?authSource=admin&authMechanism=SCRAM-SHA-256
                JwtToken: ${{ secrets.JWT_TOKEN }}
                JwtIssuer: ${{ secrets.JWT_ISSUER }}
                JwtAudience: ${{ secrets.JWT_AUDIENCE }}
                JwtExpiryTime: ${{ secrets.JWT_EXPIRY_TIME }}
              with: 
                compose-file: "compose.yaml"
                up-flags: "--build"
                down-flags: "-v"



