# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: ['**']
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies SetUp
      run: dotnet restore Setup/SetUp/SetUp/SetUp.csproj  
    - name: Build SetUp
      run: dotnet build Setup/SetUp/SetUp/SetUp.csproj --no-restore

    - name: Restore dependencies ArticleService
      run: dotnet restore Backend/ArticleService/ArticleService/ArticleService.csproj
    - name: Build ArticleService
      run: dotnet build Backend/ArticleService/ArticleService/ArticleService.csproj --no-restore
    - name: Test Article Service
      run: dotnet test Backend/ArticleService/ArticleServiceTests/ArticleServiceTests.csproj --verbosity normal

    - name: Restore dependencies UserService
      run: dotnet restore Backend/UserService/UserService/UserService.csproj
    - name: Build ArticleService
      run: dotnet build Backend/UserService/UserService/UserService.csproj --no-restore